const INPUT_MIN_LENGTH = 2;
const INPUT_MAX_LENGTH = 40;
const TEXTAREA_INPUT_MAX_LENGTH = 400;
const PASSWORD_INPUT_MIN_LENGTH = 8;
const NAME_INPUT_PATTERN = '^[a-zA-Zs-]+$';
const BOARD_NAME_MAX_LENGTH = 20;

export {
  INPUT_MIN_LENGTH,
  INPUT_MAX_LENGTH,
  TEXTAREA_INPUT_MAX_LENGTH,
  PASSWORD_INPUT_MIN_LENGTH,
  NAME_INPUT_PATTERN,
  BOARD_NAME_MAX_LENGTH,
};
