export const SET_ALL_USERS = 'SET_ALL_USERS';
export const SET_USER = 'SET_USER';
export const SET_USER_BOARDS = 'SET_USER_BOARDS';
export const SET_BOARD_COLUMNS = 'SET_BOARD_COLUMNS';
export const SET_COLUMN_TASKS = 'SET_COLUMN_TASKS';
