const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
const SET_ALL_USERS = 'SET_USERS';
const SET_USER = 'SET_USER';
const SET_BOARDS = 'SET_BOARDS';

export {
  SET_IS_LOGGED_IN,
  SET_ALL_USERS,
  SET_USER,
  SET_BOARDS,
};
